hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
          timeoutInMilliseconds: 60000
      circuitBreaker:
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 30000
        errorThresholdPercentage: 50
  booklistcall:
    execution:
      isolation:
        strategy: thread
        thread:
          timeoutInnMilliseconds: 3000
    circuitBreaker:
      requestVolumeThreshold: 10
      sleepWindowInMilliseconds: 15000
      errorThresholdPercentage: 75
    metrics:
      rollingStats:
        timeInMilliseconds: 30000
